name: Deploy Pipeline

on:
  workflow_dispatch:

jobs:
  deploy_dev:
    name: Deploy to Dev
    uses: notdodo/test-GHAs/.github/workflows/reuse.yaml@main
    with:
      environment: cane

  deploy_prod:
    name: Deploy to Prod
    needs: deploy_dev
    uses: notdodo/test-GHAs/.github/workflows/reuse.yaml@main
    with:
      environment: prod
